# Generated by Django 4.2.13 on 2024-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description_short", models.CharField(max_length=255)),
                ("description_long", models.TextField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
    ]
