# Generated by Django 4.2.13 on 2024-05-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="")),
                ("place", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="places.place")),
            ],
        ),
    ]
