# Generated by Django 4.2.13 on 2024-05-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_image__order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('place', '_order')},
        ),
    ]
