# Generated by Django 4.2.13 on 2024-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["_order"]},
        ),
        migrations.AlterField(
            model_name="image",
            name="_order",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name="Позиция"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(verbose_name="Долгота"),
        ),
    ]
