# Generated by Django 4.2.13 on 2024-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.TextField(verbose_name="Короткое описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
