# Generated by Django 4.2.13 on 2024-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_place_short_description_alter_place_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
    ]
