# Generated by Django 4.2.13 on 2024-07-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_place_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="_order",
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Файл картинки"),
        ),
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="places.place"),
        ),
    ]
