# Generated by Django 4.2.13 on 2024-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_image_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Название"),
        ),
    ]
